### ISSUE TITLE
Email user after submission

### ISSUE THREAD

**Issue by colinmxs** [colinmxs/trfrt-sbmt-api#8]
submissions@treefortmusicfest.com

**Comment by colinmxs** [comment]
need verbiage from eric

**Comment by philmerrell** [comment]
From Eric:

"Your submission to Treefort 11 has been received! We will notify all submissions of their status no later than January 15th, 2023. Submissions can be edited in the Treefort Submissions App."

The email they want to verify is submissions@treefortmusicfest.com I gave them a heads up that they'd need to click on the link that's sent.
